spring:
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.24.37:3306/clbs?useUnicode=true&characterEncoding=utf-8
      username: root
      password: Zwkj@123Mysql
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        auto-commit: true
        connection-test-query: SELECT 1
        connection-timeout: 30000
        idle-timeout: 600000
        maximum-pool-size: 100
