spring:
  cloud:
   gateway:
     loadbalancer:
       use404: true #如果服务的实例找不到,返回404
     discovery:
       locator:
         enabled: true #是否与服务发现组件进行结合(开启后,会默认为所使用服务进行转发操作(使用服务名称路由))
         lower-case-service-id: true #不必非要用大写service_id去访问了
     metrics:
       enabled: true
